[database]
host = "money-map-db"
port = 27017
name = "moneyMap"
username = "money_map_client"
password = "ds(9sj@^DFe>D;3kc"
[auth]
auth_secret = "B@4GWjJZ6bKHa1o99Bmv@nWMNh7tNR"
claim_iss = "money_map"
