refresh_rate = 5

[appender.console]
kind = "console"

[appender.file]
kind = "file"
path = "/var/lib/money_map/logs/statement_gen.log"
pattern = "%d [%t] %l %M:%m"

[root]
level = "debug"
appenders = ["file"]
